(defun bling/pre-init-helm ()
  (after 'helm-source
    (defun my-helm-make-source (f &rest args)
      (let ((source-type (cadr args))
            (props (cddr args)))
        (unless (eq source-type 'helm-source-async)
          (message "hello there")
          (plist-put props :fuzzy-match t)))
      (apply f args))
    (advice-add 'helm-make-source :around #'my-helm-make-source)))
